baseurl = "http://nats.io/"
languageCode = "en-us"
title = "NATS - Cloud Native, Open Source, High Performance Messaging"

[params]
  leftNav = false
  description = "NATS is a high performance messaging system that acts as a distributed messaging queue for cloud native applications, IoT device messaging, and microservices architecture."
  author = "The NATS team"
  mainMenu=[ "about", "download", "documentation", "support", "community", "blog" ]
